### ISSUE TITLE
[Bug] blank page on fresh install

### ISSUE THREAD

**Issue by marcinwrochna** [DifuseHQ/Kalmia#7]
I'm trying to run Kalmia, but when I open it in the browser, I get a blank page, and nothing suspicious in logs.
The html and all the many js and css files are loaded properly, there are no errors or warnings in the browser console (beyond a failed favicon.ico), yet the page has no content beyond the `<noscript>You need to enable JavaScript to run this app.</noscript><div id="root" ></div>` (no DOM nodes added).

The docker logs show no problems, in either production or dev mode, with logLevel: debug.

Browsers tried: Firefox (with adblock disabled), Chrome, Chromium, Android Firefox.
Versions tried: 0.0.2 and 4b84f90 (with and without the page_groups fix mentioned in another issue).

I'm using Traefik as a reverse proxy to provide a TLS wrapping endpoint and map everything from kalmia.REDACTED.pl to the http://kalmia:2727 container in a custom 'ntraefik' docker network - this works fine, both the kalmia server and the s3 minio webui console can be accessed via `kalmia.REDACTED.pl` and `s3ui.REDACTED.pl` respectively, the content of the public `kamlia` bucket can be accessed via `https://s3.blekot.pl/kalmia/example.txt`. The postgres connection works.

I tried `https://kalmia.REDACTED.pl/` and `https://kalmia.REDACTED.pl/doc/`.

### config.json
```json
{
  "environment": "dev",
  "port": 2727,
  "database": "postgres://kalmia:REDACTED-C@kalmia_postgres:5432/kalmia?sslmode=disable",
  "logLevel": "debug",
  "sessionSecret": "REDACTED",
  "users": [
    {
      "username": "admin",
      "email": "REDACTED",
      "password": "REDACTED",
      "admin": true
    },
    {
      "username": "user",
      "email": "user@example.com",
      "password": "user",
      "admin": false
    }
  ],
  "s3": {
    "endpoint": "http://s3:9000",
    "region": "auto",
    "accessKeyId": "REDACTED-A",
    "secretAccessKey": "REDACTED-B",
    "bucket": "kalmia",
    "usePathStyle": true,
    "publicUrlFormat": "https://s3.REDACTED.pl/kalmia/%s"
  }
}
```

### docker-compose.yaml
```yaml
services:
  kalmia:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "${PORT:-2727}:2727"
    volumes:
      - ./config.json:/app/config.json:z
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=kalmia_postgres
      - DATABASE_USER=kalmia
      - DATABASE_NAME=kalmia
      - DATABASE_PASSWORD=REDACTED-C
    depends_on:
      kalmia_postgres:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - default
      - ntraefik

  kalmia_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: kalmia
      POSTGRES_PASSWORD: REDACTED-C
      POSTGRES_DB: kalmia
    volumes:
      - ./postgres_data_v16:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kalmia -d kalmia"]
      interval: 10s
      timeout: 10s
      retries: 10

  s3:
    image: quay.io/minio/minio:latest # RELEASE.2024-09-09T16-59-28Z
    command: minio server  --console-address=":9001"  /data
    volumes:
      - ./s3data:/data:z
    environment:
      MINIO_ROOT_USER: REDACTED-A
      MINIO_ROOT_PASSWORD: REDACTED-B
      MINIO_DOMAIN: s3.REDACTED.pl
    restart: always
    networks:
      - default
      - ntraefik
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

networks:
  ntraefik:
    external: true
```

### docker-compose up logs
```
 docker-compose up
Starting kalmia_s3_1              ... done
Starting kalmia_kalmia_postgres_1 ... done
Starting kalmia_kalmia_1          ... done
Attaching to kalmia_s3_1, kalmia_kalmia_postgres_1, kalmia_kalmia_1
kalmia_postgres_1  | 
kalmia_postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
kalmia_postgres_1  | 
s3_1               | MinIO Object Storage Server
s3_1               | Copyright: 2015-2024 MinIO, Inc.
s3_1               | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
s3_1               | Version: RELEASE.2024-09-09T16-59-28Z (go1.22.7 linux/amd64)
s3_1               | 
kalmia_postgres_1  | 2024-09-11 13:55:42.922 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
kalmia_postgres_1  | 2024-09-11 13:55:42.926 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
s3_1               | API: http://172.19.0.6:9000  http://172.26.0.3:9000  http://127.0.0.1:9000 
s3_1               | WebUI: http://172.19.0.6:9001 http://172.26.0.3:9001 http://127.0.0.1:9001 
s3_1               | 
s3_1               | Docs: https://docs.min.io
kalmia_postgres_1  | 2024-09-11 13:55:42.927 UTC [1] LOG:  listening on IPv6 address "::", port 5432
kalmia_postgres_1  | 2024-09-11 13:55:42.933 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
kalmia_postgres_1  | 2024-09-11 13:55:42.953 UTC [28] LOG:  database system was shut down at 2024-09-11 13:55:38 UTC
kalmia_postgres_1  | 2024-09-11 13:55:42.973 UTC [1] LOG:  database system is ready to accept connections
kalmia_1           |  _   __      _           _
kalmia_1           | | | / /     | |         (_)
kalmia_1           | | |/ /  __ _| |_ __ ___  _  __ _
kalmia_1           | |    \ / _` | | '_ ` _ \| |/ _` |
kalmia_1           | | |\  \ (_| | | | | | | | | (_| |
kalmia_1           | \_| \_/\__,_|_|_| |_| |_|_|\__,_|
kalmia_1           |                        v0.0.2
kalmia_1           | 
kalmia_1           | 2024-09-11T13:55:53.967Z INFO db/db.go:119 Database initialized
kalmia_1           | 2024-09-11T13:55:53.968Z INFO db/cache.go:22 Cache initialized
kalmia_1           | 2024-09-11T13:55:53.970Z INFO app/main.go:124 Starting server {"port": 2727}
kalmia_1           | 2024-09-11T13:55:53.971Z DEBUG services/docs_rspress.go:263 Starting DocService.StartupCheck
kalmia_1           | 2024-09-11T13:56:07.494Z DEBUG services/docs_rspress.go:336 NPM cache initialized {"elapsed": "3.092377369s"}
kalmia_1           | 2024-09-11T13:56:07.497Z DEBUG services/docs_rspress.go:297 Startup checks complete
kalmia_postgres_1  | 2024-09-11 14:00:43.049 UTC [26] LOG:  checkpoint starting: time
kalmia_postgres_1  | 2024-09-11 14:00:43.084 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.021 s, total=0.035 s; sync files=2, longest=0.020 s, average=0.011 s; distance=0 kB, estimate=0 kB; lsn=0/19C2F28, redo lsn=0/19C2EF0
```

### Browser console
![screenshot of browser console](https://github.com/user-attachments/assets/f07fb9a8-82d9-44cb-a42c-7620555f7f77)

  * **Operating System** Linux, Fedora 40
